apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend
  labels:
    app: counter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      labels: counter-backend
    spec:
      containers:
        - name: counter-backend
          image: ghcr.io/ebholi/counter-backend:v1
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-password
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-name